### ISSUE TITLE
helper is not loaded

### ISSUE THREAD

**Issue by caecity43** [vifreefly/kimuraframework#1]
I created `google_spider.rb` in `./helpers/`

```ruby
module GoogleHelper
  def time2int(time)
    time.to_i
  end
end
```

run console:

```bash
kimurai console --url https://www.google.com
```

```
[1] pry(#<ApplicationSpider>)> time2int(Time.now)
```

return:

```
NoMethodError: undefined method `time2int' for #<ApplicationSpider:0x00007fc655206ed0>
Did you mean?  timeout
from (pry):1:in `console'
```

**Comment by vifreefly** [comment]
Hello @caecity43 !
Currently autoloaded only AppicationHelper, because it's `include`d to ApplicationSpider. Take a look at it: https://github.com/vifreefly/kimuraframework/blob/master/lib/kimurai/template/spiders/application_spider.rb#L6

All other helpers should be manually included into ApplicationSpider or a particular spider class. 
In your case add `include GoogleHelper` to `spiders/application_spider.rb`.

**Comment by caecity43** [comment]
Thank you very much.
