### ISSUE TITLE
How to pass argument to Spider

### ISSUE THREAD

**Issue by peyloride** [vifreefly/kimuraframework#9]
Hi,

First of all thanks for your hard work, Kimurai really helps me a lot. I'm using it in Sinatra app and controlling using web requests. But I just can't find a proper way to pass data(or args) to spider.

I'm using proxies and I have a proxy class and .fetch method in it which is returns a new proxy. What I want to do is pass this proxy to my spider. If I include my proxy class inside spider class, proxy.fetch method only works once. That's not what I want, I want to make every run with different proxy.

Is there way to pass some arguments when calling spider like ExampleSpider.crawl!(foo, bar) ?

**Comment by vifreefly** [comment]
Hello @peyloride !

This didn't work for you?

```ruby
class SimpleSpider < Kimurai::Base
  # ...
  @config = {
    proxy: -> { Proxy.fetch }
  }

  def parse(response, url:, data: {})
  end
end

SimpleSpider.crawl!
```
This way, proxy should be different each time when spider starts ( because proxy object is a lambda `-> {}` and Kimurai `.call`s it at each start ). 

You also can change proxy on every request (depends on engine) by adding: `before_request: { change_proxy: true }` config option.

**Comment by peyloride** [comment]
Thanks! I didn't think about lambdas, now it's working. 

Have a great day!
